# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('minutes', models.IntegerField(default=0)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employeeminutes',
            unique_together=set([('date', 'eid')]),
        ),
    ]
